Repository yoonhaorg/Duktown_Backend, pull requests merged in 2023-11, with the labels that each got.

#34 Feature/#15 전반적인 외박 구현(외박 신청 기획 구체화 전)
  src/main/java/com/duktown/domain/comment/controller/CommentController.java
  src/main/java/com/duktown/domain/sleepoverApply/controller/SleepoverApplyController.java
  src/main/java/com/duktown/domain/sleepoverApply/dto/SleepoverApplyDto.java
  src/main/java/com/duktown/domain/sleepoverApply/entity/EnumApproved.java
  src/main/java/com/duktown/domain/sleepoverApply/entity/SleepoverApply.java
  src/main/java/com/duktown/domain/sleepoverApply/entity/SleepoverApplyRepository.java
  src/main/java/com/duktown/domain/sleepoverApply/service/SleepoverApplyService.java
  src/main/java/com/duktown/global/exception/CustomErrorType.java
Labels: 담당: 김혜수, 도메인: 외박신청

#35 Feature/#9 이메일 인증 구현
  .gitignore
  build.gradle
  src/main/java/com/duktown/domain/emailCert/dto/EmailCertDto.java
  src/main/java/com/duktown/domain/emailCert/entity/EmailCert.java
  src/main/java/com/duktown/domain/emailCert/entity/EmailCertRepository.java
  src/main/java/com/duktown/domain/emailCert/service/EmailCertService.java
  src/main/java/com/duktown/domain/user/controller/UserController.java
  src/main/java/com/duktown/domain/user/dto/UserDto.java
  src/main/java/com/duktown/domain/user/service/UserService.java
  src/main/java/com/duktown/global/config/EmailConfig.java
  src/main/java/com/duktown/global/config/ProjectConfig.java
  src/main/java/com/duktown/global/config/SecurityConfig.java
  src/main/java/com/duktown/global/config/WebConfig.java
  src/main/java/com/duktown/global/email/MailService.java
  src/main/java/com/duktown/global/exception/CustomErrorType.java
  src/main/resources/application.yml
  src/test/java/com/duktown/unit/user/controller/UserControllerTest.java
  src/test/java/com/duktown/unit/user/service/UserServiceTest.java
Labels: 담당: 곽태영, 작업: feature, 도메인: 회원가입/로그인

#37 Feature/#28 외박 신청 기능 추가에 따른 추가 구현
  src/main/java/com/duktown/domain/sleepoverApply/controller/SleepoverApplyController.java
  src/main/java/com/duktown/domain/sleepoverApply/dto/SleepoverApplyDto.java
  src/main/java/com/duktown/domain/sleepoverApply/entity/EnumApproved.java
  src/main/java/com/duktown/domain/sleepoverApply/entity/SleepoverApply.java
  src/main/java/com/duktown/domain/sleepoverApply/service/SleepoverApplyService.java
  src/main/java/com/duktown/global/exception/CustomErrorType.java
  src/main/java/com/duktown/global/type/ApprovalType.java
Labels: 작업: feature, 담당: 김혜수, 작업: refactor, 도메인: 외박신청

#39 Feature/#38 로그아웃, 아이디 찾기, 비밀번호 찾기 기능 구현
  src/main/java/com/duktown/domain/emailCert/dto/EmailCertDto.java
  src/main/java/com/duktown/domain/emailCert/service/EmailCertService.java
  src/main/java/com/duktown/domain/user/controller/UserController.java
  src/main/java/com/duktown/domain/user/dto/UserDto.java
  src/main/java/com/duktown/domain/user/entity/User.java
  src/main/java/com/duktown/domain/user/service/UserService.java
  src/main/java/com/duktown/global/config/SecurityConfig.java
  src/main/java/com/duktown/global/exception/CustomErrorType.java
Labels: 담당: 곽태영, 작업: feature, 도메인: 회원가입/로그인

#43 Feature/#26 수리요청 구현
  src/main/java/com/duktown/domain/repairApply/controller/RepairApplyController.java
  src/main/java/com/duktown/domain/repairApply/dto/RepairApplyDto.java
  src/main/java/com/duktown/domain/repairApply/entity/RepairApply.java
  src/main/java/com/duktown/domain/repairApply/entity/RepairApplyRepository.java
  src/main/java/com/duktown/domain/repairApply/service/RepairApplyService.java
  src/main/java/com/duktown/domain/repairApply/service/RepairApplyServiceImpl.java
  src/main/resources/application.yml
Labels: 담당: 곽태영, 작업: feature, 도메인: 수리 요청, 담당: 정소희
