Repository yoonhaorg/Duktown_Backend, pull requests merged in 2023-10, with the labels that each got.

#11 Feature/#10 로그인/회원가입 외 endpoint AccessDenied 문제 해결
  src/main/java/com/duktown/domain/user/service/UserService.java
  src/main/java/com/duktown/global/security/SecurityConfig.java
  src/main/java/com/duktown/global/security/dto/LoginRequestDto.java
  src/main/java/com/duktown/global/security/filter/CustomAuthenticationFilter.java
  src/main/java/com/duktown/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/duktown/global/security/filter/JwtAuthorizationFilter.java
  src/main/java/com/duktown/global/security/handler/UserAuthenticationFailureHandler.java
  src/main/java/com/duktown/global/security/handler/UserAuthenticationSuccessHandler.java
  src/main/java/com/duktown/global/security/provider/JwtTokenProvider.java
  src/main/java/com/duktown/global/security/provider/UserAuthenticationProvider.java
  src/main/java/com/duktown/global/security/service/CustomUserDetails.java
  src/test/java/com/duktown/unit/user/controller/UserControllerTest.java
Labels: 담당: 곽태영, 도메인: 회원가입/로그인, 작업: fix

#14 FIX/#13 변경된 인증방식으로 일상 기능 구현
  src/main/java/com/duktown/domain/daily/controller/DailyController.java
  src/main/java/com/duktown/domain/daily/dto/DailyDto.java
  src/main/java/com/duktown/domain/daily/entity/Daily.java
  src/main/java/com/duktown/domain/daily/entity/DailyRepository.java
  src/main/java/com/duktown/domain/daily/service/DailyService.java
Labels: 담당: 김혜수, 도메인: 일상, 작업: fix

#16 Feature/#12 댓글 기능 구현
  src/main/java/com/duktown/domain/comment/controller/CommentController.java
  src/main/java/com/duktown/domain/comment/dto/CommentDto.java
  src/main/java/com/duktown/domain/comment/entity/Comment.java
  src/main/java/com/duktown/domain/comment/entity/CommentRepository.java
  src/main/java/com/duktown/domain/comment/service/CommentService.java
  src/main/java/com/duktown/domain/daily/entity/DailyRepository.java
  src/main/java/com/duktown/domain/delivery/entity/DeliveryRepository.java
  src/main/java/com/duktown/domain/market/entity/MarketRepository.java
  src/main/java/com/duktown/global/exception/CustomErrorType.java
  src/main/java/com/duktown/global/util/DateUtil.java
Labels: 담당: 곽태영, 도메인: 공통, 작업: feature

#22 Feature/#20 일상, 장터 기능 게시글 기능으로 통합
  src/main/java/com/duktown/domain/comment/controller/CommentController.java
  src/main/java/com/duktown/domain/comment/dto/CommentDto.java
  src/main/java/com/duktown/domain/comment/entity/Comment.java
  src/main/java/com/duktown/domain/comment/entity/CommentRepository.java
  src/main/java/com/duktown/domain/comment/service/CommentService.java
  src/main/java/com/duktown/domain/daily/controller/DailyController.java
  src/main/java/com/duktown/domain/daily/dto/DailyDto.java
  src/main/java/com/duktown/domain/daily/entity/DailyRepository.java
  src/main/java/com/duktown/domain/daily/service/DailyService.java
  src/main/java/com/duktown/domain/like/dto/LikeDto.java
  src/main/java/com/duktown/domain/like/entity/Like.java
  src/main/java/com/duktown/domain/like/entity/LikeRepository.java
  src/main/java/com/duktown/domain/like/service/LikeService.java
  src/main/java/com/duktown/domain/market/entity/Market.java
  src/main/java/com/duktown/domain/market/entity/MarketRepository.java
  src/main/java/com/duktown/domain/post/controller/PostController.java
  src/main/java/com/duktown/domain/post/dto/PostDto.java
  src/main/java/com/duktown/domain/post/entity/Post.java
  src/main/java/com/duktown/domain/post/entity/PostRespository.java
  src/main/java/com/duktown/domain/post/service/PostService.java
  src/main/java/com/duktown/global/exception/CustomErrorType.java
  src/main/java/com/duktown/global/type/Category.java
Labels: 담당: 곽태영, 도메인: 일상, 도메인: 장터, 작업: refactor, 도메인: 게시글

#24 Feature/#17 게시글 좋아요 여부, 개수 표시/ 배달팟 좋아요 제거
  src/main/java/com/duktown/domain/comment/service/CommentService.java
  src/main/java/com/duktown/domain/like/dto/LikeDto.java
  src/main/java/com/duktown/domain/like/entity/Like.java
  src/main/java/com/duktown/domain/like/entity/LikeRepository.java
  src/main/java/com/duktown/domain/like/service/LikeService.java
  src/main/java/com/duktown/domain/post/controller/PostController.java
  src/main/java/com/duktown/domain/post/dto/PostDto.java
  src/main/java/com/duktown/domain/post/entity/Post.java
  src/main/java/com/duktown/domain/post/service/PostService.java
  src/main/java/com/duktown/global/exception/CustomErrorType.java
Labels: 담당: 곽태영, 도메인: 공통, 작업: feature, 작업: fix

#26 Feature/#25 게시글에 댓글개수 표시
  src/main/java/com/duktown/domain/post/dto/PostDto.java
  src/main/java/com/duktown/domain/post/service/PostService.java
Labels: 담당: 곽태영, 작업: feature, 도메인: 게시글

#29 Feature/#27 DB 변경 및 auto_increment 전략 변경
  build.gradle
  src/main/java/com/duktown/domain/cleaning/entity/Cleaning.java
  src/main/java/com/duktown/domain/comment/entity/Comment.java
  src/main/java/com/duktown/domain/delivery/entity/Delivery.java
  src/main/java/com/duktown/domain/dormCert/entity/DormCert.java
  src/main/java/com/duktown/domain/emailCert/entity/EmailCert.java
  src/main/java/com/duktown/domain/like/entity/Like.java
  src/main/java/com/duktown/domain/post/entity/Post.java
  src/main/java/com/duktown/domain/repairApply/entity/RepairApply.java
  src/main/java/com/duktown/domain/replaceApply/entity/ReplaceApply.java
  src/main/java/com/duktown/domain/semester/entity/Semester.java
  src/main/java/com/duktown/domain/sleepoverApply/entity/SleepoverApply.java
  src/main/java/com/duktown/domain/unit/entity/Unit.java
  src/main/java/com/duktown/domain/userDelivery/entity/UserDelivery.java
  src/main/java/com/duktown/domain/withdrawalUser/entity/WithdrawalUser.java
  src/main/resources/application.yml
Labels: 담당: 곽태영, 작업: refactor
