Repository yoonhaorg/Duktown_Backend, pull requests merged in 2024-01, with the labels that each got.

#47 Feature/#44 청소 배정/완료/확인 기본로직 구현 및 벌점 테이블 생성
  src/main/java/com/duktown/DuktownApplication.java
  src/main/java/com/duktown/domain/cleaning/controller/CleaningController.java
  src/main/java/com/duktown/domain/cleaning/dto/CleaningDto.java
  src/main/java/com/duktown/domain/cleaning/entity/Cleaning.java
  src/main/java/com/duktown/domain/cleaning/entity/CleaningRepository.java
  src/main/java/com/duktown/domain/cleaning/service/CleaningService.java
  src/main/java/com/duktown/domain/myPage/controller/MyPageController.java
  src/main/java/com/duktown/domain/myPage/dto/PenaltyPointsDto.java
  src/main/java/com/duktown/domain/myPage/dto/UnitDto.java
  src/main/java/com/duktown/domain/myPage/service/MyPageService.java
  src/main/java/com/duktown/domain/penaltyPoints/PenaltyPoints.java
  src/main/java/com/duktown/domain/penaltyPoints/PenaltyPointsRepository.java
  src/main/java/com/duktown/domain/repairApply/controller/RepairApplyController.java
  src/main/java/com/duktown/domain/repairApply/entity/RepairApply.java
  src/main/java/com/duktown/domain/repairApply/service/RepairApplyServiceImpl.java
  src/main/java/com/duktown/domain/sleepoverApply/controller/SleepoverApplyController.java
  src/main/java/com/duktown/domain/sleepoverApply/dto/SleepoverApplyDto.java
  src/main/java/com/duktown/domain/sleepoverApply/entity/SleepoverApply.java
  src/main/java/com/duktown/domain/sleepoverApply/entity/SleepoverApplyRepository.java
  src/main/java/com/duktown/domain/sleepoverApply/service/SleepoverApplyService.java
  src/main/java/com/duktown/domain/unit/entity/UnitInitDB.java
  src/main/java/com/duktown/domain/unit/entity/UnitRepository.java
  src/main/java/com/duktown/global/type/CleaningPenaltyPoints.java
Labels: 작업: feature, 담당: 김혜수, 도메인: 청소

#48 Feature/#41 이미지 전송 기능 제외 채팅 기능 개발 완료
  build.gradle
  src/main/java/com/duktown/domain/BaseTimeEntity.java
  src/main/java/com/duktown/domain/chat/controller/ChatController.java
  src/main/java/com/duktown/domain/chat/dto/ChatDto.java
  src/main/java/com/duktown/domain/chat/entity/Chat.java
  src/main/java/com/duktown/domain/chat/entity/ChatRepository.java
  src/main/java/com/duktown/domain/chat/service/ChatService.java
  src/main/java/com/duktown/domain/chatRoom/controller/ChatRoomController.java
  src/main/java/com/duktown/domain/chatRoom/dto/ChatRoomDto.java
  src/main/java/com/duktown/domain/chatRoom/entity/ChatRoom.java
  src/main/java/com/duktown/domain/chatRoom/entity/ChatRoomRepository.java
  src/main/java/com/duktown/domain/chatRoom/service/ChatRoomService.java
  src/main/java/com/duktown/domain/chatRoomUser/controller/ChatRoomUserController.java
  src/main/java/com/duktown/domain/chatRoomUser/dto/ChatRoomUserDto.java
  src/main/java/com/duktown/domain/chatRoomUser/entity/ChatRoomUser.java
  src/main/java/com/duktown/domain/chatRoomUser/entity/ChatRoomUserRepository.java
  src/main/java/com/duktown/domain/chatRoomUser/service/ChatRoomUserService.java
  src/main/java/com/duktown/domain/comment/dto/CommentDto.java
  src/main/java/com/duktown/domain/comment/service/CommentService.java
  src/main/java/com/duktown/domain/delivery/controller/DeliveryController.java
  src/main/java/com/duktown/domain/delivery/dto/DeliveryDto.java
  src/main/java/com/duktown/domain/delivery/entity/Delivery.java
  src/main/java/com/duktown/domain/delivery/entity/DeliveryRepository.java
  src/main/java/com/duktown/domain/delivery/service/DeliveryService.java
  src/main/java/com/duktown/domain/like/dto/LikeDto.java
  src/main/java/com/duktown/domain/post/dto/PostDto.java
  src/main/java/com/duktown/domain/post/entity/Post.java
  src/main/java/com/duktown/domain/post/service/PostService.java
  src/main/java/com/duktown/global/chat/ChatPreHandler.java
  src/main/java/com/duktown/global/config/ProjectConfig.java
  src/main/java/com/duktown/global/config/StompConfig.java
  src/main/java/com/duktown/global/exception/ChatErrorHandler.java
  src/main/java/com/duktown/global/exception/CustomErrorType.java
  src/main/java/com/duktown/global/exception/CustomExceptionHandler.java
  src/main/java/com/duktown/global/kisa_SEED/KISA_SEED_CBC.java
  src/main/java/com/duktown/global/kisa_SEED/SEED.java
  src/main/java/com/duktown/global/type/ChatRoomUserType.java
  src/main/java/com/duktown/global/type/ChatType.java
  src/main/java/com/duktown/global/util/DateUtil.java
Labels: 담당: 곽태영, 작업: feature, 도메인: 배달팟

#52 [FIX #41] SockJs 지원 해제, Websocket 연결은 jwt 토큰 인증 안하도록 수정
  src/main/java/com/duktown/global/config/SecurityConfig.java
  src/main/java/com/duktown/global/config/StompConfig.java
Labels: 담당: 곽태영, 작업: fix, 도메인: 배달팟

#51 Feature/#46 외박신청& 수리 요청 추가 구현 부분
  src/main/java/com/duktown/domain/cleaning/controller/CleaningController.java
  src/main/java/com/duktown/domain/post/entity/PostRespository.java
  src/main/java/com/duktown/domain/repairApply/controller/RepairApplyController.java
  src/main/java/com/duktown/domain/repairApply/dto/RepairApplyDto.java
  src/main/java/com/duktown/domain/repairApply/entity/RepairApply.java
  src/main/java/com/duktown/domain/repairApply/entity/RepairApplyRepository.java
  src/main/java/com/duktown/domain/repairApply/service/RepairApplyService.java
  src/main/java/com/duktown/domain/repairApply/service/RepairApplyServiceImpl.java
  src/main/java/com/duktown/domain/sleepoverApply/controller/SleepoverApplyController.java
  src/main/java/com/duktown/domain/sleepoverApply/dto/SleepoverApplyDto.java
  src/main/java/com/duktown/domain/sleepoverApply/entity/Address.java
  src/main/java/com/duktown/domain/sleepoverApply/entity/SleepoverApply.java
  src/main/java/com/duktown/domain/sleepoverApply/entity/SleepoverApplyRepository.java
  src/main/java/com/duktown/domain/sleepoverApply/service/SleepoverApplyService.java
  src/main/java/com/duktown/domain/unit/entity/Unit.java
Labels: 도메인: 수리 요청, 담당: 김혜수, 도메인: 외박신청

#53 Feature/#49 마이페이지 기능 일부 구현
  src/main/java/com/duktown/domain/comment/entity/CommentRepository.java
  src/main/java/com/duktown/domain/comment/service/CommentService.java
  src/main/java/com/duktown/domain/delivery/entity/DeliveryRepository.java
  src/main/java/com/duktown/domain/like/service/LikeService.java
  src/main/java/com/duktown/domain/post/entity/PostRepository.java
  src/main/java/com/duktown/domain/post/service/PostService.java
  src/main/java/com/duktown/domain/profile/controller/ProfileController.java
  src/main/java/com/duktown/domain/profile/dto/ProfileDto.java
  src/main/java/com/duktown/domain/profile/service/ProfileService.java
  src/main/java/com/duktown/domain/user/dto/UserDto.java
  src/main/java/com/duktown/domain/user/entity/User.java
  src/test/java/com/duktown/unit/user/controller/UserControllerTest.java
  src/test/java/com/duktown/unit/user/service/UserServiceTest.java
Labels: 담당: 곽태영, 작업: feature, 도메인: 마이페이지

#54 [FEAT #41] 채팅방 상세조회 시 조회한 사용자의 아이디, 익명 번호인 getRequestUserId, getRequestUserNumber과 채팅방 인원 수 chatRoomUserCnt 응답값 추가 반환 구현
  src/main/java/com/duktown/domain/chatRoom/dto/ChatRoomDto.java
  src/main/java/com/duktown/domain/chatRoom/service/ChatRoomService.java
Labels: 담당: 곽태영, 작업: feature, 도메인: 배달팟

#55 [FIX #41] 나가기한 채팅방도 참여중인 채팅방 목록으로 조회되는 문제 해결
  src/main/java/com/duktown/domain/chatRoom/service/ChatRoomService.java
Labels: 담당: 곽태영, 작업: fix, 도메인: 배달팟

#56 Feature/#50 게시글 부분(장터,일상) + 배달팟 검색 기능
  src/main/java/com/duktown/domain/delivery/controller/DeliveryController.java
  src/main/java/com/duktown/domain/delivery/entity/DeliveryRepository.java
  src/main/java/com/duktown/domain/delivery/service/DeliveryService.java
  src/main/java/com/duktown/domain/myPage/controller/MyPageController.java
  src/main/java/com/duktown/domain/post/controller/PostController.java
  src/main/java/com/duktown/domain/post/entity/PostRepository.java
  src/main/java/com/duktown/domain/post/service/Post1PageCache.java
  src/main/java/com/duktown/domain/post/service/PostService.java
  src/main/java/com/duktown/domain/sleepoverApply/controller/SleepoverApplyController.java
  src/main/java/com/duktown/domain/sleepoverApply/entity/SleepoverApply.java
  src/main/java/com/duktown/domain/sleepoverApply/service/SleepoverApplyService.java
  src/main/java/com/duktown/domain/user/entity/User.java
Labels: 작업: feature, 담당: 김혜수, 도메인: 게시글

#59 Feature/#58 댓글 작성 시 익명 이름 부여
  src/main/java/com/duktown/domain/comment/dto/CommentDto.java
  src/main/java/com/duktown/domain/comment/entity/Comment.java
  src/main/java/com/duktown/domain/comment/entity/CommentRepository.java
  src/main/java/com/duktown/domain/comment/service/CommentService.java
  src/main/java/com/duktown/domain/like/entity/Like.java
  src/main/java/com/duktown/domain/userDelivery/entity/UserDelivery.java
  src/main/java/com/duktown/global/exception/CustomExceptionHandler.java
Labels: 담당: 곽태영, 도메인: 공통, 작업: feature

#60 Feature/#58 댓글 조회 시 익명 댓글 작성자 외 글쓴이도 구분하도록 수정
  src/main/java/com/duktown/domain/comment/entity/CommentRepository.java
  src/main/java/com/duktown/domain/comment/service/CommentService.java
Labels: 담당: 곽태영, 도메인: 공통, 작업: fix

#64 Feature/#63 마이페이지 기능 구현 및 채팅관련 오류 수정
  src/main/java/com/duktown/domain/chat/dto/ChatDto.java
  src/main/java/com/duktown/domain/chat/service/ChatService.java
  src/main/java/com/duktown/domain/chatRoom/dto/ChatRoomDto.java
  src/main/java/com/duktown/domain/chatRoom/service/ChatRoomService.java
  src/main/java/com/duktown/domain/chatRoomUser/entity/ChatRoomUserRepository.java
  src/main/java/com/duktown/domain/comment/dto/CommentDto.java
  src/main/java/com/duktown/domain/comment/entity/CommentRepository.java
  src/main/java/com/duktown/domain/delivery/dto/DeliveryDto.java
  src/main/java/com/duktown/domain/delivery/entity/DeliveryRepository.java
  src/main/java/com/duktown/domain/delivery/service/DeliveryService.java
  src/main/java/com/duktown/domain/post/entity/Post.java
  src/main/java/com/duktown/domain/post/entity/PostRepository.java
  src/main/java/com/duktown/domain/post/service/Post1PageCache.java
  src/main/java/com/duktown/domain/post/service/PostService.java
  src/main/java/com/duktown/domain/profile/dto/ProfileDto.java
  src/main/java/com/duktown/domain/profile/service/ProfileService.java
  src/main/java/com/duktown/domain/user/controller/UserController.java
  src/main/java/com/duktown/domain/user/entity/User.java
  src/main/java/com/duktown/domain/user/entity/UserRepository.java
  src/main/java/com/duktown/domain/user/service/UserService.java
  src/main/java/com/duktown/global/exception/CustomErrorType.java
Labels: 담당: 곽태영, 작업: feature, 작업: fix, 도메인: 배달팟, 도메인: 마이페이지

#67 Fix/#65 배포 전 테스트에서 발견한 오류들 수정 및 보안을 위한 암호화 코드 추가
  build.gradle
  src/main/java/com/duktown/domain/cleaning/controller/CleaningController.java
  src/main/java/com/duktown/domain/cleaning/dto/CleaningDto.java
  src/main/java/com/duktown/domain/cleaning/service/CleaningService.java
  src/main/java/com/duktown/domain/comment/dto/CommentDto.java
  src/main/java/com/duktown/domain/comment/entity/Comment.java
  src/main/java/com/duktown/domain/comment/service/CommentService.java
  src/main/java/com/duktown/domain/delivery/service/DeliveryService.java
  src/main/java/com/duktown/domain/like/service/LikeService.java
  src/main/java/com/duktown/domain/user/service/UserService.java
  src/main/java/com/duktown/global/config/JasyptConfig.java
  src/main/java/com/duktown/global/exception/CustomErrorType.java
  src/main/java/com/duktown/global/type/ChatType.java
  src/main/resources/application.yml
  src/test/java/com/duktown/JasyptTest.java
Labels: 담당: 곽태영, 작업: fix

#69 Feature/#68 2차 통합테스트 추가 반영
  build.gradle
  src/main/java/com/duktown/domain/cleaning/controller/CleaningController.java
  src/main/java/com/duktown/domain/cleaning/dto/CleaningDto.java
  src/main/java/com/duktown/domain/cleaning/entity/Cleaning.java
  src/main/java/com/duktown/domain/cleaning/service/CleaningService.java
  src/main/java/com/duktown/domain/cleaningUnit/entity/CleaningUnit.java
  src/main/java/com/duktown/domain/myPage/service/MyPageService.java
  src/main/java/com/duktown/domain/penaltyPoints/entity/PenaltyPointsRepository.java
Labels: 담당: 김혜수, 작업: refactor

#70 Feature/#68 대타 API 및 청소 테스트 완료
  src/main/java/com/duktown/domain/cleaning/controller/CleaningController.java
  src/main/java/com/duktown/domain/cleaning/dto/CleaningDto.java
  src/main/java/com/duktown/domain/cleaning/service/CleaningService.java
  src/main/java/com/duktown/domain/replaceApply/controller/ReplaceApplyController.java
  src/main/java/com/duktown/domain/replaceApply/dto/ReplaceApplyDto.java
  src/main/java/com/duktown/domain/replaceApply/entity/ReplaceApply.java
  src/main/java/com/duktown/domain/replaceApply/entity/ReplaceApplyRepository.java
  src/main/java/com/duktown/domain/replaceApply/service/ReplaceApplyService.java
  src/main/java/com/duktown/global/exception/CustomErrorType.java
Labels: 작업: feature, 담당: 김혜수, 도메인: 청소
